In [8]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

In [9]:
G=nx.Graph()
G.add_edge(1,2)
G.add_edge(2,3)
print('#Node: %i, #Edge: %i' % (G.number_of_nodes(), G.number_of_edges()))
print('Has 3-4 edge: %s' % G.has_edge(3,4))
print(nx.to_numpy_array(G).T)
G.add_nodes_from(range(1,7))
G2=nx.Graph()
G2.add_edge(1,2, weight=3)
G2.add_edge(2,3,weight=2)
print(G2[2])

#Node: 3, #Edge: 2
Has 3-4 edge: False
[[0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]
{1: {'weight': 3}, 3: {'weight': 2}}


### The equation of the cocitation network is

$$ C_{ij} = \sum^n_{k=1} A_{ik} A_{jk} $$

In [25]:
# Read the gml file
G = nx.read_gml("./proofwikidefs_la.gml", "name")
# print(G.nodes)
def cocitation(G):
    """ 
    The algorithm to compute the cocitation index based on graphical approach
    By graphical approach, which means that we need to use networkx package to compute the edges between each pair of nodes, to find out the similarity between certain pair of nodes.
    Input:
        graph
    Output:
        cocitation results
    """
    # G.predecessors will return the a directed edge from m to n
    for i in G.nodes:
        print(f"The node {i} has directed edges from {list(G.predecessors(i))}")
    # rational: we have a list of the m to n data, then we need to see if they have overlap.
    for i in range(G.number_of_nodes):
        
    # return G_cocitation
cocitation(G)

The node Vector Space Monomorphism has directed edges with ['R-Algebraic Structure Monomorphism']
The node Vector Space Isomorphism has directed edges with ['Vector Space Automorphism', 'R-Algebraic Structure Automorphism']
The node Vector Space Epimorphism has directed edges with []
The node Vector Space Automorphism has directed edges with ['R-Algebraic Structure Automorphism']
The node Vector Notation has directed edges with ['Vector (Euclidean Space)', 'Vector (Physics)', 'Vector (Linear Algebra)']
The node Vector (Euclidean Space) has directed edges with ['Perpendicular (Linear Algebra)', 'Orthogonal (Linear Algebra)/Euclidean Space', 'Orthogonal (Linear Algebra)', 'Linearly Independent/Sequence/Real Vector Space', 'Linearly Dependent/Sequence/Real Vector Space', 'Engineering Notation', 'Angle Between Vectors', 'Linearly Independent/Sequence', 'Linearly Independent Sequence', 'Linearly Independent', 'Linearly Dependent/Sequence', 'Linearly Dependent Sequence', 'Linearly Dependent'